### ISSUE TITLE
Tokocrypto: Invalid API response message not detailed

### ISSUE THREAD

**Issue by RC-13** [Tokocrypto/hummingbot#8]
**Describe the bug**
When an invalid API key for Tokocrypto is added, the following response message is shown:
![image](https://user-images.githubusercontent.com/57189990/202598511-cb519f5a-eebd-4a19-9b75-f4c8f1ef87e6.png)
We need a better response message so that users will be aware on what could have possibly happen or the next step to take.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Start the Hummingbot client
2. Connect to Tokocrypto by running `connect tokocrypto`
3. Add random keys
...

**Release version**
Version: dev-1.10.0

**Attachments**

**Comment by toriqahmads** [comment]
Hi @RC-13 ,

Thank you for reporting the bug.
I just fixed this issue.
Commit: https://github.com/Tokocrypto/hummingbot/commit/1fb3cae2909b7bf01f80c67ebbd5f007416fd23a

Thank you

**Comment by RC-13** [comment]
Thank you @toriqahmads confirming that issue is now fixed. I will now close the ticket.
