### ISSUE TITLE
Tokocrypto: response server time log at the start of the client

### ISSUE THREAD

**Issue by RC-13** [Tokocrypto/hummingbot#9]
**Describe the bug**
Opening this ticket for confirmation if this is an expected behavior.

The following message is shown right after starting the client, although this doesn't affect the bots behavior, it's just not clear where it is coming from. Maybe this can be hidden or we just need a confirmation from the dev what triggers the message.

![image](https://user-images.githubusercontent.com/57189990/202599205-f9fee845-a3be-483b-b763-fec7c4f97773.png)

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
Similar message are seen after adding and API key and starting the strategy
![image](https://user-images.githubusercontent.com/57189990/202599032-eb817e95-b0be-478e-b3b2-aa2d732a282f.png)
![image](https://user-images.githubusercontent.com/57189990/202599058-6a6afb8f-361b-4875-89bf-18f725449426.png)

**Release version**
Version: dev-1.10.0

**Attachments**
Logs not required since message is not added in the log file

**Comment by toriqahmads** [comment]
Hi @RC-13 

Thank you for reporting the bug.
I just fixed this issue.
Commit: https://github.com/Tokocrypto/hummingbot/commit/e572d6742820ff86819315a7b7e5c1fdfce8e78c

Thank you

**Comment by RC-13** [comment]
Thank you @toriqahmads confirming that issue is now fixed. I will now close the ticket.
